-- Crear tablas
create table public.category
(
    id         bigint generated by default as identity(start with 6)
        primary key,
    active     boolean,
    created_at timestamp(6),
    type       varchar(255),
    updated_at timestamp(6)
);

alter table public.category
    owner to admin;

create table public.funko
(
    id          uuid             not null
        primary key,
    created_at  timestamp(6),
    image       varchar(255),
    name        varchar(255),
    price       double precision not null
        constraint funko_price_check
            check (price >= (0)::double precision),
    quantity    integer          not null
        constraint funko_quantity_check
            check (quantity >= 0),
    updated_at  timestamp(6),
    category_id bigint
        constraint fkd8k0mwybx88n0r972oi50lf20
            references public.category
);

alter table public.funko
    owner to admin;

create table public.users
(
    id         uuid                                not null
        primary key,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    email      varchar(255)                        not null
        constraint uk_6dotkott2kjsp8vw4d0m25fb7
            unique,
    is_deleted boolean   default false,
    name       varchar(255)                        not null,
    password   varchar(255)                        not null,
    surname    varchar(255)                        not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null,
    username   varchar(255)                        not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
);

alter table public.users
    owner to admin;

create table public.user_roles
(
    user_id uuid not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references public.users,
    roles   varchar(255)
        constraint user_roles_roles_check
            check ((roles)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[]))
    );

alter table public.user_roles
    owner to admin;

-- Insertar datos en la tabla Category
INSERT INTO public.category (id, active, created_at, type, updated_at) VALUES (1, true, '2023-11-30 14:26:57.111985', 'DISNEY', '2023-11-30 14:26:57.111985');
INSERT INTO public.category (id, active, created_at, type, updated_at) VALUES (2, true, '2023-11-30 14:27:03.048399', 'MOVIE', '2023-11-30 14:27:03.048399');
INSERT INTO public.category (id, active, created_at, type, updated_at) VALUES (3, true, '2023-11-30 14:27:07.923822', 'SERIES', '2023-11-30 14:27:07.923822');
INSERT INTO public.category (id, active, created_at, type, updated_at) VALUES (4, true, '2023-11-30 14:27:12.008234', 'SUPERHEROS', '2023-11-30 14:27:12.008234');
INSERT INTO public.category (id, active, created_at, type, updated_at) VALUES (5, true, '2023-11-30 14:27:16.600811', 'OTHER', '2023-11-30 14:27:16.600811');

-- Insertar datos en la tabla Funko
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('01f23e3e-6d44-47b2-8d77-48b1cb774c83', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/mickeymouse', 'Mickey Mouse', 19.99, 10, '2023-11-30 14:28:40.804493', 1);
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('874f872f-c30e-4089-ab33-16fd1c4d4344', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/harrypotter', 'Harry Potter', 24.99, 8, '2023-11-30 14:28:40.804493', 2);
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('1783830d-1832-466e-a444-9510cecd06c2', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/spiderman', 'Spider-Man', 14.99, 12, '2023-11-30 14:28:40.804493', 4);
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('9c688032-c485-43ae-8706-e03e1d2a19d0', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/monkeydluffy', 'Monkey D. Luffy', 34.99, 7, '2023-11-30 14:28:40.804493', 3);
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('b5e349a5-7650-4bff-8596-5cc89853179c', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/doctorwho', 'Doctor Who', 39.99, 3, '2023-11-30 14:28:40.804493', 3);
INSERT INTO public.funko (id, created_at, image, name, price, quantity, updated_at, category_id) VALUES
    ('7a47f728-e959-4c81-a45d-921f39f343bb', '2023-11-30 14:28:40.804493', 'https://www.madirex.com/funko/random', 'Random Funko', 24.99, 5, '2023-11-30 14:28:40.804493', 5);

-- Insertar datos en la tabla Users
INSERT INTO USERS (id, name, surname, username, email, password, created_at, updated_at, is_deleted)
SELECT 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b',
       'Madirex',
       'Land',
       'Madirex',
       'contact@madirex.com',
       '$2a$10$/iB5BY9exKMl6Soofb7EquzGHWm3vOPHBCBb6Cg3sWcfz9kHUyIpC',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       false WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE id = 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b');

INSERT INTO USERS (id, name, surname, username, email, password, created_at, updated_at, is_deleted)
SELECT 'd4515840-8fe2-4107-8bde-0f1c545ef4c5',
       'User',
       'User',
       'User',
       'user@madirex.com',
       '$2a$10$/iB5BY9exKMl6Soofb7EquzGHWm3vOPHBCBb6Cg3sWcfz9kHUyIpC',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       false WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE id = 'd4515840-8fe2-4107-8bde-0f1c545ef4c5');

-- Insertar datos en la tabla User_Roles
INSERT INTO USER_ROLES (user_id, roles)
SELECT 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b',
       'USER' WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE user_id = 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b' AND roles = 'USER');

INSERT INTO USER_ROLES (user_id, roles)
SELECT 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b',
       'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE user_id = 'a2bcb7b3-4c36-4073-9ab8-9d8f4a57301b' AND roles = 'ADMIN');

INSERT INTO USER_ROLES (user_id, roles)
SELECT 'd4515840-8fe2-4107-8bde-0f1c545ef4c5',
       'USER' WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE user_id = 'd4515840-8fe2-4107-8bde-0f1c545ef4c5' AND roles = 'USER');
